---
abstract: 'A glimpse at an Enlightened Perl (XML).'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Kensho-XML
no_index:
  directory:
    - inc
    - t
requires:
  XML::Generator::PerlData: 0
  XML::LibXML: 0
  XML::SAX: 0
  XML::SAX::Writer: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
